### ISSUE TITLE
Bungeecord config doesn't work

### ISSUE THREAD

**Issue by Luukth** [ValentinTh/MultiCraft-JAR-Conf#14]
When I use the BungeeCord config to setup the server the ip and port don't get configured.

**Comment by ValentinTh** [comment]
Yes, that's a current bug that I've not patched at this time. It will be done soonish.
CF : https://github.com/ValentinTh/MultiCraft-JAR-Conf/issues/13

You already can set this one manually directly on your FTP, editing config.yml file. Parameter HOST.
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/ to help you to just set IP.

**Comment by ValentinTh** [comment]
Just a question, did you use a dedicated IP or IP:Port ?

**Comment by Luukth** [comment]
I'm not at a PC at this moment, will post in about 2 hours. I did find a fix but it only worked 20% of the time.

**Comment by Luukth** [comment]
```
search1 = ^.  host:
replace1 = host: {IP}:{PORT}
```

This is what I tried, only worked when the config was generated and 20% of the time. Must say I have no idea how regular expressions work. Just did some research on google.com 😄

**Comment by ValentinTh** [comment]
Happy to see that you try to patch this one 😉
I admit that I would patch like you try.
It's probably caused by generation period which is too long, so he didn't replace values when config.yml is completely generated but way before.

Anyway, I try something different, could you try this new version ?
I will continue to find other way to patch this one.

**Comment by ValentinTh** [comment]
Hi @Luukth any news from the last patch ?

**Comment by Luukth** [comment]
```
11:22:40 [INFO] Using standard Java JCE cipher.
11:22:40 [INFO] Using standard Java compressor.
11:22:40 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:7ee0b6d:1303
11:22:41 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
11:22:41 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:41 [INFO] Attempting to Jenkins download module cmd_alert v1303
11:22:42 [INFO] Download complete
11:22:42 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:42 [INFO] Attempting to Jenkins download module cmd_find v1303
11:22:42 [INFO] Download complete
11:22:42 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:42 [INFO] Attempting to Jenkins download module cmd_list v1303
11:22:42 [INFO] Download complete
11:22:42 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:42 [INFO] Attempting to Jenkins download module cmd_send v1303
11:22:42 [INFO] Download complete
11:22:42 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:42 [INFO] Attempting to Jenkins download module cmd_server v1303
11:22:42 [INFO] Download complete
11:22:42 [INFO] Attempting to update plugin from null to ModuleVersion(build=1303, git=7ee0b6d)
11:22:42 [INFO] Attempting to Jenkins download module reconnect_yaml v1303
11:22:42 [INFO] Download complete
11:22:43 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:7ee0b6d:1303 by SpigotMC
11:22:43 [SEVERE] Exception in thread "main" 
11:22:43 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
11:22:43 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:69)
11:22:43 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
11:22:43 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
11:22:43 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
11:22:43 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:22:43 [SEVERE] Caused by: while scanning a simple key
 in 'reader', line 3, column 1:
    max-players=8
    ^
could not find expected ':'
 in 'reader', line 4, column 1:
    level-name=world
    ^

11:22:43 [SEVERE] 	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:466)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
11:22:43 [SEVERE] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
11:22:43 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:66)
11:22:43 [SEVERE] 	... 4 more

```

Using that latest bungeecord.jar.conf and clean server

Config.yml
```
host: 0.0.0.0:25565
query_port: 25565
max-players=8
level-name=world
```

**Comment by ValentinTh** [comment]
It seems that your issue comes from an other part.

config.yml from your bungee could not contain "max-players=8 level-name=world" and either not be structured like that.
Be sure, you have setup your Minecraft server to another port and in offline mode.
Bungee need one port and Minecraft server need another one.

**Comment by Luukth** [comment]
Multicraft does this by default. So to counter it we need to overwrite the default search and replace.

**Comment by ValentinTh** [comment]
Really strange.
I've never seen it before. Multicraft only load .jar which generate all files and then, yes multi craft need to overwrite content.
I will try on my side, soon as possible.

**Comment by ValentinTh** [comment]
Any news ?

**Comment by Luukth** [comment]
No it just doesn't work, I made the switch to https://pterodactyl.io/

**Comment by ValentinTh** [comment]
Ok, have a nice try on Pterodactyl ;)
I will patch this anyway.

**Comment by Luukth** [comment]
I did send multicraft support an email. They came up with this answer. I tested it but it didn't work.
```
Thank you for your inquiry. With the new 2.2.0 release you can force configuration options in the .jar.conf files. For BungeeCord you could try something like this:

[force_config]
configFile = config.yml
search1 = host
replace1 = ' 'host: {IP}:{PORT}
search2 = max_players
replace2 = ' 'max_players: {MAX_PLAYERS} 
```

**Comment by ValentinTh** [comment]
Well, I will try that, I might have understood what is the issue.
